name: AGC-MineTools
version: '${project.version}'
main: me.fabichan.agcminetools.MineTools
api-version: '1.20'
load: STARTUP

commands: 
  lookup:
    description: Lookup a Player
    usage: /<command> <player>
  ban:
    description: Ban a Player
    usage: /<command> <player> [reason]
  unban:
    description: Unban a Player
    usage: /<command> <player>
  kick:
    description: Kick a Player
    usage: /<command> <player> [reason]
  op:
    description: Give a user operator permission
    usage: /<command> <player>
  deop:
    description: Remove a user from operator
    usage: /<command> <player>