name: AGC-MineTools
version: '${project.version}'
main: me.fabichan.agcminetools.MineTools
api-version: '1.20'
load: STARTUP

commands: 
  lookup:
    description: Lookup a Player
    usage: /<command> <player>
    permission: agcminetools.team
    default: op